script new

diff --git a/10-install-script b/10-install-script
--- a/10-install-script
+++ b/10-install-script
@@ -1,41 +1,42 @@
-#!bin/bash
+#1/bin/bash
 
 USERID=$(id -u)
 
-if [ $USERID -ne 0 ]
+VALIDATE(){
+    if [ $1 -ne 0 ]
+    then
+         echo "$2 .... failure"
+         exit 1
+     else    
+         echo "$2 .... success"
+      fi
+}
+
+if [ $? -ne 0 ]
 then
-    echo "ERROR: you must have sudo access to run this script"
-    exit 1
+     echo "ERROR: you must have sudo access to run the script"
+     exit 1
 fi
 
 dnf list installed mysql
 
 if [ $? -ne 0 ]
 then
-   dnf install mysql -y
-   if [ $? -ne 0 ]
-      then
-   echo "installing mysql... failure"
-   exit 1
-     else 
-     echo "installing mysql...success"
-   fi
-   else
-       echo "mysql is already....Installed"
-    fi   
-    
-    dnf list installed git
+    dnf install mysql -y
+    VALIDATE $? "Installing my sql"
+    else
+         echo "mysql already installed"
+fi
 
-    if [ $? -ne 0 ]
-    then
-        dnf install git -y
-      if [$? -ne 0 ] 
-      then
-      echo "installing git ... failure"
-      exit 1
-          else echo " installing git .... success"
-          fi
-    else 
-    echo "git already installed"
-    fi
+dnf list installed git
+
+if [ $? -ne 0 ]
+   then
+         dnf install git -y
+         VALIDATE $? "installig .... git"
+   else
+        echo "git is already .... Installed"
+fi
      
+
+        
