script new

diff --git a/10-install-script b/10-install-script
--- a/10-install-script
+++ b/10-install-script
@@ -7,4 +7,19 @@ then
     echo "ERROR: you must have sudo access to run this script"
     exit 1
 fi
-    
+
+dnf list installed mysql
+
+if [ $? -ne 0 ]
+then
+   dnf install mysql -y
+   if [ $? -ne 0 ]
+      then
+   echo "installing mysql... failure"
+   exit 1
+     else 
+     echo "installing mysql...success"
+   fi
+   else
+       echo "mysql is already....Installed"
+    fi   
