script new

diff --git a/10-install-script b/10-install-script
--- a/10-install-script
+++ b/10-install-script
@@ -23,3 +23,19 @@ then
    else
        echo "mysql is already....Installed"
     fi   
+    
+    dnf list installed git
+
+    if [ $? -ne 0 ]
+    then
+        dnf install git -y
+      if [$? -ne 0 ] 
+      then
+      echo "installing git ... failure"
+      exit 1
+          else echo " installing git .... success"
+          fi
+    else 
+    echo "git already installed"
+    fi
+     
