inst script

diff --git a/11-git-install b/11-git-install
--- a/11-git-install
+++ b/11-git-install
@@ -1,26 +1,29 @@
 #!/bin/bash
+
 USERID=$(id -u)
 
 if [ $USERID -ne 0 ]
 then
-echo "failure.. need sudo access"
-exit 1
+  echo "failure.. need sudo access"
+  exit 1
 fi
 
+# Check if mysql is already installed
 
-dnf list installed mysql
+dnf list installed mysql &>/dev/null
 
-if [ $? -ne 0 ] then
-    ech0 "mysql not found.. installing mysql"
-     dnf install mysql -y 
+if [ $? -ne 0 ]
+then
+  echo "mysql not found.. installing mysql"
+  dnf install mysql -y
 
-      if [ $? -ne 0 ]
-      then
-echo "installing mysql...Failure"
-exit 1
+  if [ $? -ne 0 ]
+  then
+    echo "installing mysql...Failure"
+    exit 1
+  else
+    echo "mysql installing.... success"
+  fi
 else
-echo "mysql installing.... success"
-fi
-else
-     echo "mysql already....Installed"
+  echo "mysql already....Installed"
 fi
