s

diff --git a/16-set b/16-set
--- a/16-set
+++ b/16-set
@@ -1,5 +1,12 @@
 #/bin/bash
 set -e
+
+error(){
+      echo "There is an error" 
+}
+
+trap error ERR
+
 echo "Hello.."
 echo "before error.."
 dvavvefrve
