s

diff --git a/16-set b/16-set
--- a/16-set
+++ b/16-set
@@ -1,11 +1,7 @@
 #/bin/bash
 set -e
-
-error(){
-      echo "There is an error in $LINENO, command is:$BASH_COMMAND" 
-}
-
-trap error ERR
+ 
+trap 'echo "There is an error in $LINENO, Command is: $BASH_COMMAND"' ERR
 
 echo "Hello.."
 echo "before error.."
